### ISSUE TITLE
Api Base URL

### ISSUE THREAD

**Issue by phyothiha-codigo** [raywenderlich/video-ysfa-materials#1]
https://api.kodeco.com/api/content?filter[content_types][]=collection is still working? It returns 404

**Comment by mataharimau** [comment]
https://api.kodeco.com/api/contents works, note contents not content

documentation hasn't been rebranded yet: https://raywenderlich.docs.apiary.io/

**Comment by phyothiha-codigo** [comment]
Oh Ok, Thanks
